main: com.philippgitpush.Main
name: Honigstube
description: Honigstube
author: philippgitpush
website: philipp.sh
version: '1.5.0'
api-version: '1.21'
commands:
  bed:
    description: Teleportiert dich zu deinem Bett.
    usage: /bed
  sit:
    description: Setz dich hin.
    usage: /sit
  honigstube:
    description: Test-Befehl für die Plugin-Entwicklung.
    usage: /honigstube
