main: com.philippgitpush.Main
name: Honigstube
description: Honigstube
author: philippgitpush
website: philipp.sh
version: '1.4.1'
api-version: '1.21'
commands:
  bed:
    description: Teleportiert dich zu deinem Bett.
    usage: /bed
  sit:
    description: Setz dich hin.
    usage: /sit
